Controllers/AwardsController.cs
using BusinessLogic.Abstracts;
using BusinessLogic.Localization;
using BusinessLogic.Models;
using System.Web.Mvc;

namespace AwardsApp.Controllers
{
    [Authorize]
    public class AwardsController : Controller
    {
        private readonly IAwardService _awardsService;
        private readonly IDraughtService _draughtService;

        public AwardsController(IAwardService awardService, IDraughtService draughtService)
        {
            _awardsService = awardService;
            _draughtService = draughtService;
        }

        /// <summary>
        /// Show the awards page
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            // get all awrds
            var awards = _awardsService.GetAwards();
            ViewBag.Alert = TempData["Alert"];

            return View(awards);

        }

        /// <summary>
        /// Create a ward
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Create(long? id)
        {
            var award = new AwardVm
            {
                Order = _awardsService.GetNextOrder()
            };
            if (id != null)
            {
                award = _awardsService.GetAwardVm((long)id);
                ViewBag.Draughts = new SelectList(_draughtService.GetDraughts(), "Id", "Name", award != null ? award.DraughtId : 0);
                if (award == null)
                {
                    ViewBag.Alert = new ResultVm { Status = false, Message = ArabicResources.InvalidData };
                    return View();
                }
                return View(award);
            }

            ViewBag.Draughts = new SelectList(_draughtService.GetDraughts(), "Id", "Name");
            ViewBag.Alert = TempData["Alert"];
            return View(award);
        }

        public ActionResult Save(AwardVm award)
        {
            if (!ModelState.IsValid)
                return View("Create", award);

            var result = _awardsService.SaveAward(award);

            if (!result.Status)
            {
                ViewBag.Alert = result;
                ViewBag.Draughts = new SelectList(_draughtService.GetDraughts(), "Id", "Name");
                return View("Create", award);
            }


            TempData["Alert"] = result;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(long id)
        {
            TempData["Alert"] = _awardsService.DeleteAward(id);
            return RedirectToAction("Index");
        }
    }
}

Views/Awards/Create.cshtml
@using BusinessLogic.Models
@model AwardVm

@{ 
    var draughts = ViewBag.Draughts as SelectList;
}

@section BodyClasses{
    admin
}

@Html.Partial("Alert")

<div class="panel panel-primary mt-50">
    <div class="panel-heading">
        <span class="caption">
            اضافة جائزة جديدة
        </span>
        <div class="actions">
            <a class="btn btn-sm btn-success" href="@Url.Action("Index")">
                <i class="fa fa-undo"></i>
            </a>
        </div>
    </div>
    <div class="panel-body">
        <div class="form-horizontal">
            @using (Html.BeginForm("Save", "Awards", FormMethod.Post))
            {
                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.Name, "الاسم")
                    </div>
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                        @Html.HiddenFor(m => m.Id)
                        <span class="help-block">
                            @Html.ValidationMessageFor(m => m.Name)
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.Value, "القيمة")
                    </div>
                    <div class="col-md-5">
                        @Html.TextBoxFor(m => m.Value, new { @class = "form-control", type ="number" })
                        <span class="help-block">
                            @Html.ValidationMessageFor(m => m.Value)
                        </span>
                    </div>
                    <div class="col-md-5">
                        @Html.TextBoxFor(m => m.Unit, new { @class = "form-control" })
                        <span class="help-block">
                            @Html.ValidationMessageFor(m => m.Unit)
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.Code, "الكود")
                    </div>
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Code, new { @class="form-control"})
                        <span class="help-block">
                            @Html.ValidationMessageFor(m => m.Code)
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.Order, "الترتيب")
                    </div>
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Order, new { @class="form-control", type="number"})
                        <span class="help-block">
                            @Html.ValidationMessageFor(m => m.Order)
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.DraughtId, "السحب")
                    </div>
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.DraughtId, draughts, new {  @class ="form-control" })
                        <span class="help-block">
                            @Html.ValidationMessageFor(m => m.DraughtId)
                        </span>
                    </div>
                </div>
                <div class="text-right border-top mt-20">
                    <button class="btn btn-success" type="submit">
                        حفظ
                    </button>
                </div>
            }
        </div>
    </div>
</div>

Views/Awards/Index.cshtml
@using BusinessLogic.Models
@model List<AwardVm>

@Html.Partial("Alert")

@section BodyClasses{
    admin    
}
<div class="panel panel-primary mt-50 awards-section">
    <div class="panel-heading">
        <span class="caption">
            الجوائز
        </span>
        <div class="actions">
            <a class="btn btn-sm btn-success" href="@Url.Action("Create")">
                <i class="fa fa-edit"></i>
            </a>
        </div>
    </div>
    <div class="panel-body">
        <div class="table-section">
            @if (Model.Any())
            {
                <table>
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                الاسم
                            </th>
                            <th>
                                القيمة
                            </th>
                            <th>
                                الكود
                            </th>
                            <th>
                                السحب
                            </th>
                            <th>
                                خيارات
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var award in Model)
                        {
                            <tr>
                                <td>
                                    @award.Order
                                </td>
                                <td>@award.Name</td>
                                <th>@award.Value  @award.Unit</th>
                                <td>@award.Code</td>
                                <td>@award.DraughtName</td>
                                <td>
                                    <div class="btn-group parent">
                                        <a class="btn btn-sm btn-info" href="@Url.Action("Create", new { id = award.Id })">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <form class="hidden" method="post" action="@Url.Action("Delete")">
                                            <input type="hidden" name="id" value="@award.Id" />
                                        </form>
                                        <a class="btn btn-sm btn-danger delete" href="#">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-warning">
                    لا يوجد جوائز حتى الان
                </div>
            }

        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/Awards")
    <script type="text/javascript">
        AwardsScript.OnDeleteClick();
    </script>
}