Controllers/DraughtController.cs
using BusinessLogic.Abstracts;
using BusinessLogic.Localization;
using BusinessLogic.Models;
using BusinessLogic.ViewModels;
using System.Web.Mvc;

namespace AwardsApp.Controllers
{
    [Authorize]
    public class DraughtController : Controller
    {
        #region Fields
        private readonly IDraughtService _draughtService;
        #endregion

        public DraughtController(IDraughtService draughtService)
        {
            _draughtService = draughtService;
        }


        #region Mvc Actions
        /// <summary>
        /// Show all draughts
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            // get all draughts
            var draughts = _draughtService.GetDraughts();
            ViewBag.Alert = TempData["Alert"];

            return View(draughts);
        }

        public ActionResult Create(long? id)
        {
            var draught = new DraughtVm();

            if (id != null)
            {
                draught = _draughtService.GetDraughtVm((long)id);
                if (draught == null)
                {
                    ViewBag.Alert = new ResultVm { Status = false, Message = ArabicResources.InvalidData };
                    return View();
                }
            }
            ViewBag.Alert = TempData["Alert"];
            return View(draught);
        }
        public ActionResult Save(DraughtVm draught)
        {
            if (draught.Id == 0 && draught.BackgroundFile == null)
                ModelState.AddModelError("BackgroundFile", ArabicResources.ImageIsRequired);

            if (!ModelState.IsValid)
                return View("Create", draught);

            var result = _draughtService.SaveDraught(draught);

            if (!result.Status)
            {
                ViewBag.Alert = result;
                return View("Create", draught);
            }


            TempData["Alert"] = result;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(long id)
        {
            TempData["Alert"] = _draughtService.DeleteDraught(id);
            return RedirectToAction("Index");
        }

        public ActionResult CounterSpeed()
        {
            ViewBag.Alert = TempData["Alert"];
            return View(_draughtService.GetCounterSpeed());
        }

        [HttpPost]
        public ActionResult CounterSpeed(CounterSpeedVm counterSpeedVm)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("CounterSpeed", counterSpeedVm);

            TempData["Alert"] = _draughtService.SaveCounterSpeed(counterSpeedVm);
            return RedirectToAction("CounterSpeed");
        }
        #endregion

    }
}

Views/Draught/CounterSpeed.cshtml
@using BusinessLogic.ViewModels

@model CounterSpeedVm

@Html.Partial("Alert")

@section BodyClasses{
    admin
}

<div class="panel panel-primary mt-50">
    <div class="panel-heading">
        <span class="caption">
           سرعة عداد السحب
        </span>
    </div>
    <div class="panel-body">
        <div class="form-horizontal">
            @using (Html.BeginForm("CounterSpeed", "Draught", FormMethod.Post))
            {
                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.Speed, "  سرعة عداد السحب بالثوانى")
                    </div>
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Speed, new { @class = "form-control" })
                        <span class="help-block">
                            @Html.ValidationMessageFor(m => m.Speed)
                        </span>
                    </div>
                </div>
                <div class="text-right border-top mt-20">
                    <button class="btn btn-success" type="submit">
                        حفظ
                    </button>
                </div>
            }
        </div>
    </div>
</div>

Views/Draught/Create.cshtml
@using BusinessLogic.Models;

@model DraughtVm

@Html.Partial("Alert")

@section BodyClasses{
    admin    
}

<div class="panel panel-primary mt-50">
    <div class="panel-heading">
        <span class="caption">
            اضافة سحب جديدة
        </span>
        <div class="actions">
            <a class="btn btn-sm btn-success" href="@Url.Action("Index")">
                <i class="fa fa-undo"></i>
            </a>
        </div>
    </div>
    <div class="panel-body">
        <div class="form-horizontal">
            @using (Html.BeginForm("Save", "Draught", FormMethod.Post, new {enctype = "multipart/form-data" }))
            {
                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.Name, "الاسم")
                    </div>
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                        @Html.HiddenFor(m => m.Id)
                        <span class="help-block">
                            @Html.ValidationMessageFor(m => m.Name)
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.Value, "القيمة")
                    </div>
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Value, new { @class = "form-control"})
                        <span class="help-block">
                            @Html.ValidationMessageFor(m => m.Value)
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.IsActive, "فعال")
                    </div>
                    <div class="col-md-10">
                        @Html.CheckBoxFor(m => m.IsActive)
                        <span class="help-block">
                            @Html.ValidationMessageFor(m => m.IsActive)
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.BackgroundFile, "الخلفية")
                    </div>
                    <div class="col-md-10">
                        @if(Model != null && Model.BackgroundPath != null)
                        {
                            <div class="thumbnail">
                                @Html.HiddenFor(m => m.BackgroundPath)
                                <img src="@Model.BackgroundPath" width="200" />
                            </div>
                        }
                        @Html.TextBoxFor(m => m.BackgroundFile, new { @class = "form-control", type = "file" })
                        <span class="help-block">
                            @Html.ValidationMessageFor(m => m.BackgroundFile)
                        </span>
                    </div>
                </div>
                <div class="text-right border-top mt-20">
                    <button class="btn btn-success" type="submit">
                        حفظ
                    </button>
                </div>
            }
        </div>
    </div>
</div>

Views/Draught/Index.cshtml
@using BusinessLogic.Models
@model List<DraughtVm>

@Html.Partial("Alert")

@section BodyClasses{
    admin
}

<div class="panel panel-primary mt-50 awards-section">
    <div class="panel-heading">
        <span class="caption">
            السحب
        </span>
        <div class="actions">
            <a class="btn btn-sm btn-success" href="@Url.Action("Create")">
                <i class="fa fa-edit"></i>
            </a>
        </div>
    </div>
    <div class="panel-body">
        <div class="table-section">
            @if (Model.Any())
            {
                <table>
                    <thead>
                        <tr>
                            <th>
                                الاسم
                            </th>
                            <th>
                                القيمة
                            </th>
                            <th>
                                فعال
                            </th>
                            <th>
                                الخلفية
                            </th>
                            <th>
                                خيارات
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var draught in Model)
                        {
                            <tr>
                                <td>@draught.Name</td>
                                <td>@draught.Value</td>
                                <td>
                                    <span class="label @(draught.IsActive ? "label-success": "label-danger")">
                                        <i class='fa @(draught.IsActive ? "fa-check": "fa-times")'></i>
                                    </span>
                                </td>
                                <td>
                                    <div class="img-thumbnail">
                                        <img src="@draught.BackgroundPath"  width="50" height="50"/>
                                    </div>
                                </td>
                                <td>
                                    <div class="btn-group parent">
                                        <a class="btn btn-sm btn-info" href="@Url.Action("Create", new { id = draught.Id })">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <form class="hidden" method="post" action="@Url.Action("Delete")">
                                            <input type="hidden" name="id" value="@draught.Id" />
                                        </form>
                                        <a class="btn btn-sm btn-danger delete" href="#">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-warning">
                    لا يوجد سحب حتى الان
                </div>
            }

        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/Awards")
    <script type="text/javascript">
        AwardsScript.OnDeleteClick();
    </script>
}